# Generated by Django 4.2.6 on 2023-10-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('affected', models.CharField(max_length=2048)),
                ('automatic', models.BooleanField()),
                ('note', models.CharField(max_length=1024)),
            ],
        ),
    ]
