# Generated by Django 4.2.6 on 2023-10-26 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nebula_backend', '0004_alter_alt_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nebula_backend.raider')),
            ],
        ),
        migrations.DeleteModel(
            name='Alt',
        ),
        migrations.AddField(
            model_name='raider',
            name='main',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nebula_backend.character'),
        ),
    ]
