# Generated by Django 4.2.6 on 2023-10-26 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nebula_backend', '0005_character_delete_alt_raider_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='owner',
        ),
    ]
