# Generated by Django 4.2.6 on 2023-10-29 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nebula_backend', '0010_loggedaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoggedAction',
        ),
    ]
