# Generated by Django 4.2.6 on 2023-10-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nebula_backend', '0011_delete_loggedaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='raider',
            name='discord_nickname',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
