# Generated by Django 4.2.6 on 2023-11-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nebula_backend', '0013_alter_raider_discord_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raider',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
