# Generated by Django 4.2.6 on 2023-11-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nebula_backend', '0014_alter_raider_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raider',
            name='main',
        ),
        migrations.AddField(
            model_name='character',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
