# Generated by Django 4.2.6 on 2023-11-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nebula_backend', '0015_remove_raider_main_character_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raider',
            name='discord_nickname',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
