# Generated by Django 4.2.6 on 2023-11-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nebula_backend', '0016_alter_raider_discord_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='raider',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
