# Generated by Django 4.2.6 on 2023-10-30 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nebula_backend', '0012_raider_discord_nickname'),
        ('nebula_attendance', '0004_event_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nebula_attendance.event')),
                ('raider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nebula_backend.raider')),
            ],
        ),
    ]
