# Generated by Django 4.2.6 on 2023-10-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nebula_attendance', '0005_attendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='intime',
            field=models.CharField(choices=[('A', 'INTIME'), ('B', 'SLIGHT DELAY'), ('C', 'LONG DELAY')], default='B', max_length=1),
            preserve_default=False,
        ),
    ]
